Jekyll 3 support
slim-template/jekyll-slim pull request #5
Opened 2016-03-15 05:14 UTC by dmitryzuev

Updated version of `jekyll-slim` gem, now using new version of `sliq`.

If someone provide slim files with liquid tags for testing, it will be great

2016-03-15 20:39 UTC, minad commented
@dmitryzuev I also added you to this repository and gem. Thx for your efforts!

2016-03-15 20:40 UTC, dmitryzuev commented
@minad thanks :)
I'll merge this when I'll be sure that it works well

2016-04-27 14:33 UTC, socialphotos commented
@dmitryzuev have you had time to review it?

2016-04-29 07:10 UTC, karir-workstation commented
Any clue when will this updates be merged?

2016-04-29 11:09 UTC, socialphotos commented
@karir-workstation to use this branch add this code to jekyll Gemfile
```
group :jekyll_plugins do
  gem 'sliq', github: 'dmitryzuev/sliq', branch: 'feature-versions-update'
  gem 'jekyll-slim', :github => 'dmitryzuev/jekyll-slim', :branch => 'feature-jekyll3'
end
```

2016-09-22 08:49 UTC, seuros commented on lib/jekyll/slim/version.rb
> +    VERSION = '0.11.0'
this should be bumper to a bigger version , maybe 0.20.0

2016-09-22 08:49 UTC, seuros commented on jekyll-slim.gemspec
> +  gem.add_runtime_dependency 'byebug'
debug gem should be removed

2016-09-22 08:50 UTC, seuros commented on testapp/.gitignore
> +_site
we can remove the testapp.

2016-09-22 08:51 UTC, seuros requested changes
I tested these change, and they work perfectly.

Let some comments

2016-10-11 13:54 UTC, brandonsturgeon commented
Hey @socialphotos , I'm getting non-https warnings with your snippet there. I can't quite figure out how to reference a specific branch with a url, though. Any thoughts?

2017-02-21 04:23 UTC, rlue commented on lib/jekyll/slim/version.rb
> +    VERSION = '0.11.0'
From the [Semantic Versioning specification](http://semver.org/):

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. **Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.**

2017-02-21 04:28 UTC, rlue commented on jekyll-slim.gemspec
> +  gem.add_runtime_dependency 'byebug'
debug gem should be ~~removed~~ listed with `add_development_dependency` instead. (Bundler inherits dependencies from the gemspec, and if byebug isn't specified, it's going to break someone's development workflow.)

2017-04-04 13:05 UTC, donv commented
@dmitryzuev @minad Could you merge this?  I'd like to contribute, and it would be easier if I could work against master.

2017-05-16 10:23 UTC, donv commented
@minad Any chance you could merge this?

2017-05-20 13:51 UTC, minad commented
@donv do you want to maintain this library?

2017-05-21 13:51 UTC, seuros commented
@minad my branch is the most up to date one.

2017-05-21 15:10 UTC, minad commented
@seuros I can also add you if you want. what is missing here is a maintainer...

2017-05-21 15:31 UTC, seuros commented
Sure thing.

2017-05-22 09:22 UTC, donv commented
@minad Yes, I can maintain this library for the coming year at least.

2017-05-22 20:06 UTC, minad commented
Ok, I invited you both

2017-05-23 10:13 UTC, donv commented
Joined.  Thanks!

2019-03-06 15:04 UTC, d-Pixie commented
@minad @donv @seuros How come this is still not fixed/merged? 🙂

2019-03-06 15:27 UTC, minad commented
@d-Pixie Since no one is maintaining this package currently.

2019-03-06 16:12 UTC, seuros approved these changes

2019-03-06 16:58 UTC, merged